sudo: required

notifications:
email: james.hn.sears@gmail.com

env:
  global:
    # travis encrypt COVERITY_SCAN_TOKEN=...
    - secure: "D61zXfiLh2wwVJAlKujmteEOftUk/CSFgMDRvUwTij4fJ9mGz5ACnnlw717BuehIIOxyUpKceJwYMm8e965Vk03Piuhcur44mFGmXFNu3LToNWaSiYPpA1ryGhvNoXLdiumn9RhFM8fOqlqo2WyIBIcpv5EmLIYm443yRZ5YYABuYhWuCgUVc7f5GYvZOs1jdSWDLTNsJtznULjzJMw97TlTHf/z/PbH35OM3TPcwPGgnwCi3uAvd9SrYOPvWOQaCePFcqSq6OUKmWyYgsjBGXJCMOESNqVLgJjkOZEijuRNqu82NA61ls3wqSX9tWdA0XO3ogCZTL5DCX0QYDwsnsuycEELA9TmCXZoB3oQFfYYkxhRrIOYjV9zy4lU8xAOuA3A4KaMfA5/Tx/8CoWOnFe67AHmT5vW3Ki2RYF1zmdSq4dnKTZ5rkAMFyjFcNz/LxCMcQ/wnacRZlR+b0pYRSlnbMk4F4ikSAC9EgfGiSGVessddtS4Y08xKWefKG4gXrFb2Jli38JzoSOo6Peh+h2gwApQegp7Yv2N7TA/frG9Dppuy+1DvO6BDNNE2BHoakyF9/4LNpXTjIVBOuPOtLICiGalZmHUNcg1hk8/27mGZqNMKEqLtiw/bgt07caFXxfmEOK4JhXt5lT8B/8NyqQaROxTMpdcMq4WJ2RIsTg="
    # travis encrypt COVERALLS_REPO_TOKEN=...
    - secure: "P+kM+0d6viBPR/APxTlEh1GYbi7XfoBpsNwMYFN+w6PFz0WTzn/yqDJD9mG/kmLQItbnPVcxhnOpGzsdMvrbZ8yjTSRjYeYM7WcN3LNq33qyrz2K4e4EvSSdONvptth87Veod+C6OWbZF9/rN5BmTp2Ichy4niaTJMCPsJQlTjTq2f6QoIfnHKTC9hAfa4bSfjJWUNhH8GmgH3bHUFuVpU/Ja0GGHPlhtH6snPV+eu/+PiR429laMvbRUqbSd+CxIU2RX20xV6HHYDH1ZAvoH7kid+zYNDbmKnMYq1XiiCgxLO9fm/hdON66IslwA8Ym5M5Zpv9/3KN1hnfENuHvv9KTLCjqDgIJRWD410EsNSQRdyW3JoUe36eS7YxupZ7UVO4QhPsOlj7jUSLaq4IYlfrSveTbB7Df1FRerh5bQ2X5WLIdSwOhhpmIAL5gg8lI2pBJ7GXjjSjbMPFYApGb8o3UmUcwuBVx5lSk2KgPnxw/d77OZkN+yHuJdHrGrnSCI1vTdB1duwSQpxOEwAB84HischcnsikLhBn++nGEuR/h/CWNSAoAfbv0AWGhk0lHSZEqt57UT3QcMaT2UNpnUHTPTgibrBSrmg5WmQ5abA5tpfEjgKm+l4TfZUP/srTzav6J6wDZ4olOLVn8fS6lPB4QxE10fW7FxOvGplKfvDM="
    # travis encrypt CODACY_PROJECT_TOKEN=...
    - secure: "qjKZEJEz9YgktsLO83X6Rd+NzhQBcneKRbNn6WTWIeAhqcbj2zDPuryOKBBofwWYCMBYqD19nygZYqvS9cy8V73jPmHb1SynuRHNitFFKioV4/HXmHYsVZEbZZudOP30XXSy6wdHrTZZhZr5jtNLAAjjb4S10bxWUOMCznPzHExn+d0TulTqK89VbHx7CDYsqN1yRo/4+07W31a64vgZ59A2L7KFTL+T++LqqkIgZiwcudos5kpPdVnj0HtIHnQ1lvCjtFZeM8YTUtXUkW+Gwv6P/vIQdNK1THPtQE5y5Eo56P1cO9bwdQ0SJSTt/zzSTnjlwvW/f1RkF0jaJaa26jiY93i1SH+cK2GH5TUwvgMJlrsrDHIaQsoWv+ppTRYq/8U0oE5EYQR2y4SzIhne32SmPeYw7Rubko9JiGVM15UjewTGk2QDCz0NH/kwv4twYcYc2Fbw/30rc1NFMyyz5Bw143nZVxoQLi/9H7BfueYJ7m4oZOzcTUp+aKtTjDu1s+/8xKId82lpKQ5Sr64DNYEqCD2z7u3yX6Q7/dBUO8jNN8yMp59GMlXa4d8ebcTqYEOEoLDOICPOQkJUB32JB3Ek/Qq2yPjRYIiSc1a9OjQHvXHmHgp18thPFQI3M9rZzTxeq47Uo/AN9RPnyJMOU/qg37fNAi/WLJaAUpFDGiM="

addons:
  sonarcloud:
    organization: "jameshnsears-github"
    token:
      secure: "lgG+TMvMZsfsiz8GtWriFAjc6P581cKHAjtbGHlqeNtf4wMyzmuOaIrPR8H8aVbHusRq4HwYIA22IGdFQNF7gMEbb4LEC9k9t9avDT7/L0BgqITm7jMvEQgpUahSsh299siAsrIqiA+ZdXTf+3lr0vU3K+PllXwmdPH/TmJDrnSgpJzzAthcW91xMUywJbmT8ojtra71/ROeu5560KNxrP8+yufsviA8OyB+nZhutsPePoYqlpBZwaypYmh4pvQAdDSDtFoCROgRzgLVFWaCL0o5WTwip2k5Hke+WXvPGRG+ltR87FTW/RtJmjA9h9qsofCBhNcf+S/bTDsjPUJezOhVQe1hLZAQaXig6E0bUQRoukQVEwI76l6DRmS9rTb6IwfUp6GK5gbiS4c0QiB34lRHPQ2dVf7F6AFCk2DOisYD6vEE3uCxLelUXJ6DZOfKLIzqs1z3Q7Xfnp+uCePpEticJo83wJgLvqr/bHULnTpKoL+dDW5/VJ1ROEhgskJMx2+Noa6jOaQbD1d5lBS9z4lV6vaQCXpjEWkkIPz6uIvIiB5R71bBrPOePqOJjGWQU/pCBO8U4ZS/XzHReZwkQkLXra7jWYR7NvOTa4/iC+gTKgq5ZJk/fU/iA+mg7OUNHahXfXWONlcNr/tgS/s9tc93ZBcw5jV8A2BuSl2EWXw="

  coverity_scan:
    project:
      name: jameshnsears/pytest-docker-py
      version: HEAD
      description: pytest-docker-py
    notification_email: james.hn.sears@gmail.com
    build_command_prepend: ""
    build_command: "pytest -s test/unit"
    branch_pattern: master

git:
  depth: false

services:
  - docker

cache:
  directories:
  - $HOME/.sonar/cache

language: python

python:
  - "3.6"

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - export PYTHONPATH=src:test:$PYTHONPATH
  - flake8 src test
  - pylint --rcfile=setup.cfg src test -r n > pylint-report.txt 2>&1 || true

script:
  - pytest -s --cov-report term-missing --cov . test/unit
  - mkdir coverage
  - mv .coverage coverage/.coverage.0

  - pip install git+https://github.com/jameshnsears/pytest-docker-py@master
  - pytest -s --cov-report term-missing --cov . test
  - mv .coverage coverage/.coverage.1
  - cd coverage
  - coverage combine
  - coverage xml -i
  - mv .coverage coverage.xml ..
  - cd ..

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - sonar-scanner

after_failure:
  - docker images
  - docker ps -a
